kiali:
  auth:
    openid:
      # in local deployment we have insecure staging
      # let's encrypt certs
      insecureSkipVerifyTls: true
  resources: ~
kiali-operator:
  resources:
    limits: ~
    requests:
      cpu: "0m"
      memory: "0Mi"
