global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress
kiali:
  auth:
    openid:
      insecureSkipVerifyTls: false
  podAnnotations:
    sidecar.istio.io/proxyCPU: 10m
    sidecar.istio.io/proxyCPULimit: 1000m
    sidecar.istio.io/proxyMemory: 64Mi
    sidecar.istio.io/proxyMemoryLimit: 80Mi
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 80Mi
subDomain: kiali
