global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress
kiali:
  auth:
    openid:
      insecureSkipVerifyTls: false
  resources:
    limits:
      cpu: "0m"
      memory: "0Mi"
    requests:
      cpu: "0m"
      memory: "0Mi"
kiali-operator:
  allowAdHocKialiImage: true
  debug:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  watchNamespace: kiali-operator
subDomain: kiali